seata:
    config:
        type: file
    service:
        grouplist:
            default: 127.0.0.1:7070
        vgroup-mapping:
            test_group: default
    tx-service-group: test_group
server:
    port: 8689
spring:
    application:
        name: seata-product
    cloud:
        nacos:
            discovery:
                password: nacos
                server-addr: localhost:8848
                username: nacos
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 654321
        url: jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
